when@dev:
    web_profiler:
        toolbar: true
        intercept_redirects: false

    framework:
        profiler: { only_exceptions: false }

when@test:
    web_profiler:
        toolbar: false
        //To intercept the mail we have to change param default false to true
        //Because when we are in development not in production 
        intercept_redirects: true

    framework:
        profiler: { collect: false }
